# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/study/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/study/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/study/project/CMakeFiles /mnt/c/study/project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/study/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TextEditor

# Build rule for target.
TextEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextEditor
.PHONY : TextEditor

# fast build rule for target.
TextEditor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/build
.PHONY : TextEditor/fast

src/Command.o: src/Command.cpp.o
.PHONY : src/Command.o

# target to build an object file
src/Command.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Command.cpp.o
.PHONY : src/Command.cpp.o

src/Command.i: src/Command.cpp.i
.PHONY : src/Command.i

# target to preprocess a source file
src/Command.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Command.cpp.i
.PHONY : src/Command.cpp.i

src/Command.s: src/Command.cpp.s
.PHONY : src/Command.s

# target to generate assembly for a file
src/Command.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Command.cpp.s
.PHONY : src/Command.cpp.s

src/FileDriver.o: src/FileDriver.cpp.o
.PHONY : src/FileDriver.o

# target to build an object file
src/FileDriver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/FileDriver.cpp.o
.PHONY : src/FileDriver.cpp.o

src/FileDriver.i: src/FileDriver.cpp.i
.PHONY : src/FileDriver.i

# target to preprocess a source file
src/FileDriver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/FileDriver.cpp.i
.PHONY : src/FileDriver.cpp.i

src/FileDriver.s: src/FileDriver.cpp.s
.PHONY : src/FileDriver.s

# target to generate assembly for a file
src/FileDriver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/FileDriver.cpp.s
.PHONY : src/FileDriver.cpp.s

src/InputData.o: src/InputData.cpp.o
.PHONY : src/InputData.o

# target to build an object file
src/InputData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputData.cpp.o
.PHONY : src/InputData.cpp.o

src/InputData.i: src/InputData.cpp.i
.PHONY : src/InputData.i

# target to preprocess a source file
src/InputData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputData.cpp.i
.PHONY : src/InputData.cpp.i

src/InputData.s: src/InputData.cpp.s
.PHONY : src/InputData.s

# target to generate assembly for a file
src/InputData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputData.cpp.s
.PHONY : src/InputData.cpp.s

src/InputHandler.o: src/InputHandler.cpp.o
.PHONY : src/InputHandler.o

# target to build an object file
src/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputHandler.cpp.o
.PHONY : src/InputHandler.cpp.o

src/InputHandler.i: src/InputHandler.cpp.i
.PHONY : src/InputHandler.i

# target to preprocess a source file
src/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputHandler.cpp.i
.PHONY : src/InputHandler.cpp.i

src/InputHandler.s: src/InputHandler.cpp.s
.PHONY : src/InputHandler.s

# target to generate assembly for a file
src/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputHandler.cpp.s
.PHONY : src/InputHandler.cpp.s

src/InputManager.o: src/InputManager.cpp.o
.PHONY : src/InputManager.o

# target to build an object file
src/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputManager.cpp.o
.PHONY : src/InputManager.cpp.o

src/InputManager.i: src/InputManager.cpp.i
.PHONY : src/InputManager.i

# target to preprocess a source file
src/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputManager.cpp.i
.PHONY : src/InputManager.cpp.i

src/InputManager.s: src/InputManager.cpp.s
.PHONY : src/InputManager.s

# target to generate assembly for a file
src/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/InputManager.cpp.s
.PHONY : src/InputManager.cpp.s

src/Log.o: src/Log.cpp.o
.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i
.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s
.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/SampleClass.o: src/SampleClass.cpp.o
.PHONY : src/SampleClass.o

# target to build an object file
src/SampleClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/SampleClass.cpp.o
.PHONY : src/SampleClass.cpp.o

src/SampleClass.i: src/SampleClass.cpp.i
.PHONY : src/SampleClass.i

# target to preprocess a source file
src/SampleClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/SampleClass.cpp.i
.PHONY : src/SampleClass.cpp.i

src/SampleClass.s: src/SampleClass.cpp.s
.PHONY : src/SampleClass.s

# target to generate assembly for a file
src/SampleClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/SampleClass.cpp.s
.PHONY : src/SampleClass.cpp.s

src/StateEditor.o: src/StateEditor.cpp.o
.PHONY : src/StateEditor.o

# target to build an object file
src/StateEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/StateEditor.cpp.o
.PHONY : src/StateEditor.cpp.o

src/StateEditor.i: src/StateEditor.cpp.i
.PHONY : src/StateEditor.i

# target to preprocess a source file
src/StateEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/StateEditor.cpp.i
.PHONY : src/StateEditor.cpp.i

src/StateEditor.s: src/StateEditor.cpp.s
.PHONY : src/StateEditor.s

# target to generate assembly for a file
src/StateEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/StateEditor.cpp.s
.PHONY : src/StateEditor.cpp.s

src/TextBuffer.o: src/TextBuffer.cpp.o
.PHONY : src/TextBuffer.o

# target to build an object file
src/TextBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/TextBuffer.cpp.o
.PHONY : src/TextBuffer.cpp.o

src/TextBuffer.i: src/TextBuffer.cpp.i
.PHONY : src/TextBuffer.i

# target to preprocess a source file
src/TextBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/TextBuffer.cpp.i
.PHONY : src/TextBuffer.cpp.i

src/TextBuffer.s: src/TextBuffer.cpp.s
.PHONY : src/TextBuffer.s

# target to generate assembly for a file
src/TextBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/TextBuffer.cpp.s
.PHONY : src/TextBuffer.cpp.s

src/UI.o: src/UI.cpp.o
.PHONY : src/UI.o

# target to build an object file
src/UI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/UI.cpp.o
.PHONY : src/UI.cpp.o

src/UI.i: src/UI.cpp.i
.PHONY : src/UI.i

# target to preprocess a source file
src/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/UI.cpp.i
.PHONY : src/UI.cpp.i

src/UI.s: src/UI.cpp.s
.PHONY : src/UI.s

# target to generate assembly for a file
src/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/UI.cpp.s
.PHONY : src/UI.cpp.s

src/iterator.o: src/iterator.cpp.o
.PHONY : src/iterator.o

# target to build an object file
src/iterator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/iterator.cpp.o
.PHONY : src/iterator.cpp.o

src/iterator.i: src/iterator.cpp.i
.PHONY : src/iterator.i

# target to preprocess a source file
src/iterator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/iterator.cpp.i
.PHONY : src/iterator.cpp.i

src/iterator.s: src/iterator.cpp.s
.PHONY : src/iterator.s

# target to generate assembly for a file
src/iterator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/iterator.cpp.s
.PHONY : src/iterator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/type.o: src/type.cpp.o
.PHONY : src/type.o

# target to build an object file
src/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/type.cpp.o
.PHONY : src/type.cpp.o

src/type.i: src/type.cpp.i
.PHONY : src/type.i

# target to preprocess a source file
src/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/type.cpp.i
.PHONY : src/type.cpp.i

src/type.s: src/type.cpp.s
.PHONY : src/type.s

# target to generate assembly for a file
src/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/src/type.cpp.s
.PHONY : src/type.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TextEditor"
	@echo "... src/Command.o"
	@echo "... src/Command.i"
	@echo "... src/Command.s"
	@echo "... src/FileDriver.o"
	@echo "... src/FileDriver.i"
	@echo "... src/FileDriver.s"
	@echo "... src/InputData.o"
	@echo "... src/InputData.i"
	@echo "... src/InputData.s"
	@echo "... src/InputHandler.o"
	@echo "... src/InputHandler.i"
	@echo "... src/InputHandler.s"
	@echo "... src/InputManager.o"
	@echo "... src/InputManager.i"
	@echo "... src/InputManager.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/SampleClass.o"
	@echo "... src/SampleClass.i"
	@echo "... src/SampleClass.s"
	@echo "... src/StateEditor.o"
	@echo "... src/StateEditor.i"
	@echo "... src/StateEditor.s"
	@echo "... src/TextBuffer.o"
	@echo "... src/TextBuffer.i"
	@echo "... src/TextBuffer.s"
	@echo "... src/UI.o"
	@echo "... src/UI.i"
	@echo "... src/UI.s"
	@echo "... src/iterator.o"
	@echo "... src/iterator.i"
	@echo "... src/iterator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/type.o"
	@echo "... src/type.i"
	@echo "... src/type.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

